/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 buildings.glb -T --shadows 
Files: buildings.glb [20.14MB] > buildings-transformed.glb [1.34MB] (93%)
Author: sumitmangela (https://sketchfab.com/sumitmangela)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/new-york-buildings-e7922fe0f7b14ed786f84529f9217dac
Title: New York Buildings
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export function Building(props) {
  const { nodes, materials } = useGLTF(
    '/models/building/buildings-transformed.glb',
  );
  return (
    <group {...props} dispose={null}>
      {/* <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_4.geometry}
        material={materials['Material.011']}
        position={[0, 0.673, -4.707]}
        scale={[0.194, 0.665, 0.194]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_6.geometry}
        material={materials['Material.012']}
        position={[0, 0.999, -5.903]}
        scale={[0.29, 1, 0.502]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_8.geometry}
        material={materials['Material.013']}
        position={[0, 0.994, -7.075]}
        scale={[0.216, 1, 0.216]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_10.geometry}
        material={materials['Material.014']}
        position={[0, 0.897, -3.655]}
        scale={[0.246, 0.893, 0.346]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_12.geometry}
        material={materials['Material.015']}
        position={[0, 0.688, -8.545]}
        scale={[0.235, 0.69, 0.654]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_14.geometry}
        material={materials['Material.016']}
        position={[0, 1.014, -2.099]}
        scale={[0.392, 1, 0.557]}
      /> */}

      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_16.geometry}
        material={materials['Material.005']}
        position={[-2.54, 1.013, -0.029]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.278, 1, 0.278]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_18.geometry}
        material={materials['Material.006']}
        position={[-3.895, 0.991, -0.029]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.286, 1, 0.286]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_20.geometry}
        material={materials['Material.007']}
        position={[-5.209, 1.021, -0.029]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.311, 1, 0.311]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_22.geometry}
        material={materials['Material.008']}
        position={[-6.582, 1.021, -0.029]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.391, 1, 0.391]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_24.geometry}
        material={materials['Material.009']}
        position={[-8.195, 1.009, -0.029]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.293, 1, 0.445]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_26.geometry}
        material={materials['Material.010']}
        position={[-9.66, 0.991, -0.029]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.286, 1, 0.286]}
      />

      {/*       
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_28.geometry}
        material={materials.empire_state}
        position={[-0.137, 4.094, 3.054]}
        scale={0.052}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_30.geometry}
        material={materials.metlife}
        position={[-0.048, 0.992, 5.192]}
        scale={[0.275, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_32.geometry}
        material={materials['tower_one.001']}
        position={[-0.226, 1.015, 1.77]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[-0.335, 1, 0.376]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_33.geometry}
        material={materials.tower_antenna}
        position={[-0.226, 1.015, 1.77]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[-0.335, 1, 0.376]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_35.geometry}
        material={materials.Material}
        position={[0, 0.61, 7.271]}
        scale={[-0.34, 1, 0.35]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_37.geometry}
        material={materials['Material.001']}
        position={[0, 0, 8.585]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_39.geometry}
        material={materials['tower_antenna.001']}
        position={[0, 1.001, 10.179]}
        scale={[0.236, 1, 0.404]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_40.geometry}
        material={materials['Material.002']}
        position={[0, 1.001, 10.179]}
        scale={[0.236, 1, 0.404]}
      /> */}
      {/* <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_43.geometry}
        material={materials['Material.004']}
        position={[0, 0.825, 12.228]}
        rotation={[-Math.PI, 0, 0]}
        scale={[-0.54, 0.823, 1.734]}
      /> */}
    </group>
  );
}

useGLTF.preload('/models/building/buildings-transformed.glb');
