/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 gari-transformed.glb 
Author: ᗩᒪE᙭. Kᗩ.🚗 (https://sketchfab.com/Alex.Ka.)
License: CC-BY-NC-ND-4.0 (http://creativecommons.org/licenses/by-nc-nd/4.0/)
Source: https://sketchfab.com/3d-models/mclaren-f1-1993-by-alexka-294df724d96241cdbe0e0f3c91ad7fce
Title: McLaren F1 1993 By Alex.Ka.🤍🖤
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export function Gari(props) {
  const { nodes, materials } = useGLTF('/models/car/gari-transformed.glb');
  return (
    <group {...props} dispose={null} castShadow>
      <mesh
        geometry={nodes.Object_2.geometry}
        material={materials.F1_front_plastic}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={1.075}
      />
      <mesh
        geometry={nodes.Object_3.geometry}
        material={materials.F1_nip_logo}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={1.075}
      />
      <mesh
        geometry={nodes.Object_4.geometry}
        material={materials.F1_red_F}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={1.075}
      />
      <mesh
        geometry={nodes.Object_5.geometry}
        material={materials.F1_red_R}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={1.075}
      />
      <mesh
        geometry={nodes.Object_6.geometry}
        material={materials.F1_side}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={1.075}
      />
      <mesh
        geometry={nodes.Object_7.geometry}
        material={materials.McLAREN_RED_LINE}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={1.075}
      />
      <mesh
        geometry={nodes.Object_8.geometry}
        material={materials.McLAREN_sidelogo}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={1.075}
      />
      <mesh
        geometry={nodes.Object_9.geometry}
        material={materials.McLAREN_sidelogo_FBUMPER}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={1.075}
      />
      <mesh
        geometry={nodes.Object_10.geometry}
        material={materials.PaletteMaterial001}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={1.075}
      />
      <mesh
        geometry={nodes.Object_11.geometry}
        material={materials.McLaren_logo}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={1.075}
      />
      <mesh
        geometry={nodes.Object_12.geometry}
        material={materials.McLaren_supportlogo}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={1.075}
      />
      <mesh
        geometry={nodes.Object_13.geometry}
        material={materials.material}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={1.075}
      />
      <mesh
        geometry={nodes.Object_14.geometry}
        material={materials.PaletteMaterial002}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={1.075}
      />
      <mesh
        geometry={nodes.Object_15.geometry}
        material={materials.PaletteMaterial003}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={1.075}
      />
      <mesh
        geometry={nodes.Object_16.geometry}
        material={materials.PaletteMaterial004}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={1.075}
      />
      <mesh
        geometry={nodes.Object_17.geometry}
        material={materials.PaletteMaterial005}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={1.075}
      />
      <mesh
        geometry={nodes.Object_18.geometry}
        material={materials.PaletteMaterial006}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={1.075}
      />
      <mesh
        geometry={nodes.Object_19.geometry}
        material={materials.bottom}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={1.075}
      />
      <mesh
        geometry={nodes.Object_20.geometry}
        material={materials.brakedisk}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={1.075}
      />
      <mesh
        geometry={nodes.Object_21.geometry}
        material={materials.brakelight}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={1.075}
      />
      <mesh
        geometry={nodes.Object_23.geometry}
        material={materials.PaletteMaterial007}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={1.075}
      />
      <mesh
        geometry={nodes.Object_24.geometry}
        material={materials.chrome2}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={1.075}
      />
      <mesh
        geometry={nodes.Object_25.geometry}
        material={materials.door_stitch}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={1.075}
      />
      <mesh
        geometry={nodes.Object_26.geometry}
        material={materials.engine}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={1.075}
      />

      <mesh
        geometry={nodes.Object_29.geometry}
        material={materials.exhaust_hole}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={1.075}
      />
      <mesh
        geometry={nodes.Object_30.geometry}
        material={materials.PaletteMaterial008}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={1.075}
      />
      {/* <mesh
        geometry={nodes.Object_31.geometry}
        material={materials.floor}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={1.075}
      /> */}
      <mesh
        geometry={nodes.Object_32.geometry}
        material={materials.front_turn_signal}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={1.075}
      />
      <mesh
        geometry={nodes.Object_34.geometry}
        material={materials.grill1}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={1.075}
      />
      <mesh
        geometry={nodes.Object_35.geometry}
        material={materials.grill2}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={1.075}
      />
      <mesh
        geometry={nodes.Object_36.geometry}
        material={materials.grill_3}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={1.075}
      />
      <mesh
        geometry={nodes.Object_37.geometry}
        material={materials.grill_f}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={1.075}
      />
      <mesh
        geometry={nodes.Object_38.geometry}
        material={materials.grill_side}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={1.075}
      />
      <mesh
        geometry={nodes.Object_39.geometry}
        material={materials.headlight_1}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={1.075}
      />
      <mesh
        geometry={nodes.Object_40.geometry}
        material={materials.headlight_2}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={1.075}
      />
      <mesh
        geometry={nodes.Object_41.geometry}
        material={materials.headlightglass}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={1.075}
      />
      <mesh
        geometry={nodes.Object_42.geometry}
        material={materials.interior}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={1.075}
      />
      <mesh
        geometry={nodes.Object_43.geometry}
        material={materials.mirrors}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={1.075}
      />

      <mesh
        geometry={nodes.Object_45.geometry}
        material={materials.material_43}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={1.075}
      />
      <mesh
        geometry={nodes.Object_46.geometry}
        material={materials.plate_F}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={1.075}
      />
      <mesh
        geometry={nodes.Object_47.geometry}
        material={materials.plate_R}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={1.075}
      />
      <mesh
        geometry={nodes.Object_50.geometry}
        material={materials.material_48}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={1.075}
      />
      <mesh
        geometry={nodes.Object_51.geometry}
        material={materials.rimbolt}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={1.075}
      />
      <mesh
        geometry={nodes.Object_52.geometry}
        material={materials.rimlogo}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={1.075}
      />
      <mesh
        geometry={nodes.Object_53.geometry}
        material={materials.side_turn_signal}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={1.075}
      />
      <mesh
        geometry={nodes.Object_54.geometry}
        material={materials.suport}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={1.075}
      />
      <mesh
        geometry={nodes.Object_55.geometry}
        material={materials.tire}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={1.075}
      />
      <mesh
        geometry={nodes.Object_56.geometry}
        material={materials.tire_side}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={1.075}
      />
      <mesh
        geometry={nodes.Object_57.geometry}
        material={materials.windo_F}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={1.075}
      />
    </group>
  );
}

useGLTF.preload('/models/car/gari-transformed.glb');
