/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 road.glb 
Author: Mini Loft Games (https://sketchfab.com/SquadCell)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/modular-roads-pack-99023ee0b2564395b47b40d22f51f7c2
Title: Modular Roads Pack
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export function Road(props) {
  const { nodes, materials } = useGLTF('/models/roads/road.glb');
  return (
    <group {...props} dispose={null}>
      {/* <group position={[0, 0, 150]} scale={0.01}>
        <mesh
          geometry={nodes.Road_L_Intersection_City_Road_mat_0.geometry}
          material={materials.City_Road_mat}
        />
        <mesh
          geometry={nodes.Road_L_Intersection_City_Intersection_mat_0.geometry}
          material={materials.City_Intersection_mat}
        />
      </group> */}
      {/* <group position={[0, 0, 100]} scale={0.01}>
        <mesh
          geometry={nodes.Road_T_Intersection_City_Intersection_mat_0.geometry}
          material={materials.City_Intersection_mat}
        />
        <mesh
          geometry={nodes.Road_T_Intersection_City_Road_mat_0.geometry}
          material={materials.City_Road_mat}
        />
      </group> */}
      {/* <group position={[0, 0, 50]} scale={0.01}>
        <mesh
          geometry={nodes.Road_X_Intersection_City_Intersection_mat_0.geometry}
          material={materials.City_Intersection_mat}
        />
        <mesh
          geometry={nodes.Road_X_Intersection_City_Road_mat_0.geometry}
          material={materials.City_Road_mat}
        />
      </group> */}
      <mesh
        geometry={nodes.Road_1X_Straight_City_Road_mat_0.geometry}
        material={materials.City_Road_mat}
        scale={0.01}
      />
      {/* <mesh
        geometry={nodes.Road_2X_Straight_City_Road_mat_0.geometry}
        material={materials.City_Road_mat}
        position={[0, 0, -50]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.Road_4X_Straight_City_Road_mat_0.geometry}
        material={materials.City_Road_mat}
        position={[-2.99, 0, -100]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.Road_4X_HalfCircle_City_Road_mat_0.geometry}
        material={materials.City_Road_mat}
        position={[-2.99, 0, -400]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.Road_2X_HalfCircle_City_Road_mat_0.geometry}
        material={materials.City_Road_mat}
        position={[0, 0, -300]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.Road_1X_HalfCircle_City_Road_mat_0.geometry}
        material={materials.City_Road_mat}
        position={[0, 0, -200]}
        scale={0.01}
      /> */}
    </group>
  );
}

useGLTF.preload('/models/roads/road.glb');
